Before running the notebook run the command `mlflow server --host 127.0.0.1 --port 5000`

In [1]:
from pathlib import Path

import mlflow
import pandas as pd
from hydra import compose, initialize
from pycaret import classification

# Load config

In [2]:
with initialize(version_base=None, config_path="../conf"):
    config = compose(config_name="health_prediction_config")

# Load data

In [3]:
health_df = pd.read_csv(Path("..") / config.silver_dataset_path)
health_df

,Age,Gender,Cholesterol,Glucose,Smoking,Alcohol Consumption,Exercise,BMI,Family History,Heart Disease,...,Stroke,Kidney Disease,Cancer,Alzheimer's Disease,COPD,Liver Disease,Parkinson's Disease,Tuberculosis,Blood Pressure_Low,Blood Pressure_Normal
0,69,0,1,1,1,0,0,35.671099,0,1,...,0,0,1,0,0,0,0,0,0,0
1,32,0,1,0,1,0,1,38.554188,1,0,...,0,0,0,0,0,1,0,0,1,0
2,89,1,1,0,0,0,1,18.932964,1,1,...,0,0,0,0,0,0,0,0,0,1
3,78,0,1,1,0,0,1,21.806350,1,0,...,1,0,1,0,0,1,0,0,0,0
4,38,0,0,0,1,1,1,37.552683,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,27,1,1,0,0,0,0,31.960176,1,1,...,0,0,0,0,0,0,0,0,1,0
996,51,1,1,0,0,1,1,20.118492,1,0,...,0,0,0,0,0,0,0,0,0,0
997,72,1,1,0,1,0,0,20.916536,1,0,...,0,0,0,0,0,0,0,0,0,1
998,49,0,1,1,1,0,1,19.560143,1,0,...,0,0,0,1,0,0,0,0,0,1
999,67,0,0,0,1,0,1,24.035803,1,0,...,1,0,0,0,1,1,0,0,0,0

# Modelling

In [4]:
# Connect to Mlflow server
mlflow.set_tracking_uri("http://127.0.0.1:5000")


# Initialize PyCaret Setup and train models
target_cols = ["Heart Disease", "Diabetes", "Stroke", "Kidney Disease", "Cancer", "Alzheimer's Disease", "COPD", "Liver Disease", "Parkinson's Disease", "Tuberculosis"]

reg_setups = {
    "with": {},
    "without": {},
}

best_models = {
    "with": {},
    "without": {},
}

comp_results = {
    "with": {},
    "without": {},
}


for col in target_cols:
    experiment_name = "health_" + col.lower().replace(" ", "_").replace("'", " ") + "_with"

    reg_setups["with"][col] = classification.setup(
        data=health_df,
        target=col,
        train_size=config.train_size,
        fix_imbalance=True,
        transformation=True,
        normalize=True,
        session_id=config.random_state,
        log_experiment=True,
        experiment_name=experiment_name,
        memory=False,
    )
    best_models["with"][col] = classification.compare_models(sort="F1")
    comp_results["with"][col] = classification.pull().copy()

    reg_setups["without"][col] = classification.setup(
        data=health_df,
        target=col,
        train_size=config.train_size,
        ignore_features=["Age", "BMI"],
        fix_imbalance=True,
        transformation=True,
        normalize=True,
        session_id=config.random_state,
        log_experiment=True,
        experiment_name=experiment_name + "out",
        memory=False,
    )
    best_models["without"][col] = classification.compare_models(sort="F1")
    comp_results["without"][col] = classification.pull().copy()

2026/08/21 14:31:17 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:17 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/ed45d3bd361241d4aba6e239f8e3b85e.
2026/08/21 14:31:17 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:18 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:18 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/3555f4f4de534a1fad682d64975d504a.
2026/08/21 14:31:18 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:19 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:19 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/4a89e3e8aef94095a6ef52c215befb1f.
2026/08/21 14:31:19 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:20 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:20 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/97dfba2c650f48a9ad664da3f965bc2c.
2026/08/21 14:31:20 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:21 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/c8c7a89819a142f68009b41cd3ca1db7.
2026/08/21 14:31:21 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:22 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:22 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/3bdea59a455948038a58157d7d93a901.
2026/08/21 14:31:22 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:23 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:23 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/45bacd95948648a6aa030f57d74995e3.
2026/08/21 14:31:23 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:24 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:24 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/e412fe16710a4d64b3432704fc5b5023.
2026/08/21 14:31:24 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:25 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:25 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/acdf9a0326694741a39fc8eb32aa9aff.
2026/08/21 14:31:25 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:26 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/b586bb4a4a9a4c9fbb3f2f323b1121cf.
2026/08/21 14:31:26 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:27 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:27 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/9528f2f647064cbeb7e1ef9dcce43e34.
2026/08/21 14:31:27 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:28 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:28 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/fb27c77d748b4da48a89d1553a39a612.
2026/08/21 14:31:28 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:29 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:29 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/c24e60ec5e9f48e08032f3da9bd5537b.
2026/08/21 14:31:29 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:30 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:30 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/dacc246a697449f895d5a72f1ff61fe7.
2026/08/21 14:31:30 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.
2026/08/21 14:31:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:31 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/296219890235609537/runs/b5adc8ffa2674450a5ee2e7c62e96be2.
2026/08/21 14:31:31 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/296219890235609537.

2026/08/21 14:31:51 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:52 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/f3bcb0d1ff7d4b21a537db0ddcf8c414.
2026/08/21 14:31:52 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:31:52 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:53 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/4362e25dfc7d4f9fa216c26da726567c.
2026/08/21 14:31:53 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:31:53 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:54 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/d82bcce494c94389975fe1a922040c0d.
2026/08/21 14:31:54 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:31:54 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:55 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/5cc2f910993f44babe848622632a2bc2.
2026/08/21 14:31:55 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:31:55 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:56 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/c01c154b8b9d45028fea66c0d2424432.
2026/08/21 14:31:56 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:31:57 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:57 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/ddf4c9f3da854d34996777f96aced6a0.
2026/08/21 14:31:57 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:31:58 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:58 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/de1fceb4333441359f45ce97c00a5e9c.
2026/08/21 14:31:58 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:31:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:31:59 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/97104a70581044fe8f811a175d171c43.
2026/08/21 14:31:59 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:32:00 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:00 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/2ea48bbedfee402bbbad364bc30a6717.
2026/08/21 14:32:00 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:32:01 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:01 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/f3cac8d090f041cea25d1007ecf31624.
2026/08/21 14:32:01 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:32:02 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:02 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/b3ebd0a0a2654071aed23c640e7147ed.
2026/08/21 14:32:02 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:32:03 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:03 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/60322ee3a9f7450aa2f54bbb3a6edbe5.
2026/08/21 14:32:03 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:32:04 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:04 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/c9cf5c94a9484b81869522c52909b0d7.
2026/08/21 14:32:04 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:32:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:05 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/5a1ad3b953fa494893adc3e254456681.
2026/08/21 14:32:05 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.
2026/08/21 14:32:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:06 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/634825436105495086/runs/6f0eb48a5a1f435e89115ac2239b8d14.
2026/08/21 14:32:06 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/634825436105495086.

2026/08/21 14:32:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:31 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/75c95c70092c4fcb899c7287c955be19.
2026/08/21 14:32:31 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:32 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:32 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/37b4c8ba7cbf430ebf374bf7867b0e1a.
2026/08/21 14:32:32 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:33 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:33 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/6e5aed8226194b7b8eb37cf70483e4fb.
2026/08/21 14:32:33 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:34 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:34 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/e6f653714f1e4b1e94fca19a6f18649f.
2026/08/21 14:32:34 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:35 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/40d9214a3b8843afb29fc7088173cb72.
2026/08/21 14:32:35 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:36 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/6429348e89bb4244847acc0182d9b395.
2026/08/21 14:32:36 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:37 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:37 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/f0ff72779bb74be283f419a5ff57ebd8.
2026/08/21 14:32:37 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:38 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/ca46094fe1b9445d8e014a7e49cba6ec.
2026/08/21 14:32:38 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:39 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/065766c8ead940dcbe1236b099b41019.
2026/08/21 14:32:39 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:39 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:40 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/c2fdda86f6b047a882df7c15e0ab84de.
2026/08/21 14:32:40 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:40 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/8d75642956fb412f84228b8d3a3595ee.
2026/08/21 14:32:40 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:41 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/112b9dd0a7c042f8946a4f200bb7cf39.
2026/08/21 14:32:41 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:42 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/8ad6078f1a474e4f96f09881fdf37bdd.
2026/08/21 14:32:42 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:43 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/9478b782274e43738a95f5de8e35d137.
2026/08/21 14:32:43 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.
2026/08/21 14:32:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:32:44 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/148140050682696434/runs/e6ea9e33f3564b9ebd8cb6f099cc778b.
2026/08/21 14:32:44 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/148140050682696434.

2026/08/21 14:33:03 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:03 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/0b7a8eefc1984989947ffea57b3e65d6.
2026/08/21 14:33:03 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:04 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:05 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/64a5c4bd719f4fb1aff3f3129161636c.
2026/08/21 14:33:05 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:05 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/e999737c00f54a6683374a50d1e2b1e5.
2026/08/21 14:33:05 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:06 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/d1406f7394534eada84ed3d4bfda0318.
2026/08/21 14:33:06 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:07 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:07 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/1c281b0f8fd6419ea6d8461dfea7cb4a.
2026/08/21 14:33:07 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:08 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/f1a9c700265043a292760188084498e9.
2026/08/21 14:33:08 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:09 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/19792beae1974f1e87d77ce771193afd.
2026/08/21 14:33:09 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:10 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:10 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/99b72bed966347a08bddc96f67a05d2b.
2026/08/21 14:33:10 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:11 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:11 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/b7112a0c947b4dadb940ef1de9849e72.
2026/08/21 14:33:11 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:12 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/69743af55e754506ad43cc6488e16471.
2026/08/21 14:33:12 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:13 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/6d303e7fd95044cab85f04fc26d61bc3.
2026/08/21 14:33:13 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:14 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:14 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/fe60731ae2cc47cd940b85b0630ef773.
2026/08/21 14:33:14 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:14 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:15 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/6209b75e30cb415ea4335b4e1262341f.
2026/08/21 14:33:15 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:16 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/7eaaf927edac499694c8e797201318d9.
2026/08/21 14:33:16 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.
2026/08/21 14:33:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:17 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/136626471325192292/runs/31bfcf88238841239e6e4740c1123b5b.
2026/08/21 14:33:17 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/136626471325192292.

2026/08/21 14:33:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:45 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/7422e1dd6e7549f4954c0e0bf4d80112.
2026/08/21 14:33:45 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:45 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:46 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/cd5f454ceff74f4da7b6c4a25ba34770.
2026/08/21 14:33:46 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:46 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/ddff71f06ef4485e8b47219afbcef5ab.
2026/08/21 14:33:46 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/0efc896ff5994601855adebcfe28e855.
2026/08/21 14:33:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:48 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/615ed0072a46444082eda73b3be1648e.
2026/08/21 14:33:48 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:49 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/5f3005e4722c415f893bf668567b7068.
2026/08/21 14:33:49 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:50 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:50 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/3a4a36d77bd144be86f00c62e30027fe.
2026/08/21 14:33:50 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:51 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:51 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/928467d270f04c568355941419b7acba.
2026/08/21 14:33:51 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:52 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:52 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/4ef2d89afb84461e8ed4fb548dcd69c2.
2026/08/21 14:33:52 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:53 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:53 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/1b0447e215424e4991e70e88dffe5c25.
2026/08/21 14:33:53 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:54 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:54 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/9abcfbf3179442e6877fe5e7b0dc9545.
2026/08/21 14:33:54 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:55 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:55 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/02f039289b4141e5a105b5580e77fbfa.
2026/08/21 14:33:55 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:55 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:56 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/bc4956237ae346bca293b776646a94a8.
2026/08/21 14:33:56 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:56 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/f13d2a6ba26b44d189acad5fcf617aeb.
2026/08/21 14:33:57 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.
2026/08/21 14:33:57 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:33:57 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/160079166971932789/runs/df8af16b38c04809bfc65b8e35d1d3f0.
2026/08/21 14:33:57 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/160079166971932789.

2026/08/21 14:34:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:16 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/354c4eaac36a40fe828f55449348cba0.
2026/08/21 14:34:16 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:17 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:17 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/919a8de0a33d4a259412d4da9a8023a9.
2026/08/21 14:34:17 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:18 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:19 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/3fa4c483e5b14903941a7f7d153ddab3.
2026/08/21 14:34:19 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:19 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:20 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/f385dc87a550411d8b67600468eaefa0.
2026/08/21 14:34:20 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:21 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/bc4c6e82d420478a8683f4013233f3a0.
2026/08/21 14:34:21 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:22 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:22 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/48bb006ef2f14577acc2ea672d77d09c.
2026/08/21 14:34:22 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:23 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:23 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/be74ad2cb0ba47b59746ca5d92b2519a.
2026/08/21 14:34:23 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:24 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:24 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/a3ac31e8744843d684a4fb656dbb9969.
2026/08/21 14:34:24 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:25 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:25 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/2530bdf327504679b3682834b60f7e3c.
2026/08/21 14:34:25 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:26 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/976380795d7243e9871fc1961e6e3437.
2026/08/21 14:34:26 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:27 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:27 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/78162464f1444e189b310f69521e4341.
2026/08/21 14:34:27 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:28 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:28 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/428f1c648512440aa67597cb36948787.
2026/08/21 14:34:28 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:29 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:29 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/0b9ca146c524403ebda292fac41c4d83.
2026/08/21 14:34:29 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:30 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:30 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/a5bd87f6d84e4256acaa150c8a7d867f.
2026/08/21 14:34:30 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.
2026/08/21 14:34:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:34:31 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/615906957830681197/runs/31f866cb82aa4d5cbe3ce37fc44fade1.
2026/08/21 14:34:31 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/615906957830681197.

2026/08/21 14:36:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:14 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/a1f4dfcfbbe341cfa2cbc79fd019c9fd.
2026/08/21 14:36:14 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:15 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/28c8b9f2782f49088e219f953fbc9b01.
2026/08/21 14:36:15 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:18 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/3b59693986384437bfc26fc5d50a16af.
2026/08/21 14:36:18 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:19 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:19 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/4ba853dc49284f8a85c1aa33eec4ee97.
2026/08/21 14:36:19 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:21 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/3c49931e2066430ab8073a0b39f40647.
2026/08/21 14:36:21 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:22 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:23 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/3021d2ed2031459191de861cb4002281.
2026/08/21 14:36:23 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:24 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:24 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/7be899b7c52b4f86b743d3ac88c9abf1.
2026/08/21 14:36:24 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:25 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:25 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/afe79225ed7c4039b458e75c7147f59f.
2026/08/21 14:36:25 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:27 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:29 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/594684dc129544729428b8cd3facf93f.
2026/08/21 14:36:29 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:32 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/d89d625c60b746178056900bae0fc4be.
2026/08/21 14:36:32 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:33 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:34 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/59b909eaa1e54c4288daae369fda628d.
2026/08/21 14:36:34 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:35 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/d74596f1c3614fccbc8acc6d079703fa.
2026/08/21 14:36:35 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:36 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/8dfb30716c2f487a81cba1206ff88f89.
2026/08/21 14:36:36 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:37 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:37 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/31f9f224fb9c4376b32808bf25bd242b.
2026/08/21 14:36:37 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.
2026/08/21 14:36:39 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:36:39 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/912370430959725788/runs/5f19682108314c8f8b00c8e03229fe64.
2026/08/21 14:36:39 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/912370430959725788.

2026/08/21 14:37:39 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:37:40 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/f189cad8002b480abf20891c1e03e522.
2026/08/21 14:37:40 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:37:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:37:41 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/f9cbc47edad44daeb039bbf3d0eb87bd.
2026/08/21 14:37:41 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:37:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:37:43 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/e4aa459019a04eeea6cd526c6847c9cb.
2026/08/21 14:37:43 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:37:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:37:45 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/645badba5fc44a4e9344c7ee46bf410e.
2026/08/21 14:37:45 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:37:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:37:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/dafe86f6174a492c81f34c4d88403b80.
2026/08/21 14:37:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:37:50 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:37:50 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/ef623e2633fa43f3aa5359adce542824.
2026/08/21 14:37:50 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:37:53 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:37:53 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/4d5ff79702194ec3917e71eaec562c94.
2026/08/21 14:37:53 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:37:55 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:37:55 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/e3f3e0f153c64367a5bb78ba8277fb62.
2026/08/21 14:37:55 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:37:57 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:37:58 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/4403b47ce2c94edd9e230eb3f0c8a5af.
2026/08/21 14:37:58 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:37:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:38:01 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/02e3c874e4f74c0cbea76b9f52caa27f.
2026/08/21 14:38:01 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:38:02 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:38:02 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/e1a111c2ba8d4868a5f2b054694965a3.
2026/08/21 14:38:02 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:38:04 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:38:04 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/c68d1bf8e8ed49cfa53cc8022a084c6e.
2026/08/21 14:38:04 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:38:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:38:06 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/04b582079fbe4cd8b82fed8ece3dba68.
2026/08/21 14:38:06 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:38:07 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:38:07 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/6115333f71d24006a16b6beb0cd65ab5.
2026/08/21 14:38:07 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.
2026/08/21 14:38:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:38:08 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/519269524664135198/runs/11cca3753e6c46ada206dca9f6208c6d.
2026/08/21 14:38:08 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/519269524664135198.

2026/08/21 14:39:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:37 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/fb12f039b7114caf9c5bc921e9ea63d3.
2026/08/21 14:39:37 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:38 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/ac1913a69925439098b8c32feca12c81.
2026/08/21 14:39:38 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:39 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:39 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/57ae98a2eca04a5ab6be0712cea9e72e.
2026/08/21 14:39:39 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:40 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/5c25e2d540fd48fa8b0aadeb00d46aa1.
2026/08/21 14:39:40 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:41 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/70265c26564345e78c270a4af63f1360.
2026/08/21 14:39:41 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:42 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/ed5ceec241a542fcbac6ba022d8f6aea.
2026/08/21 14:39:42 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:43 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/c3bf38a451e74518b7613549c8982a40.
2026/08/21 14:39:43 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:45 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/21979476521845439236e2ebe3a7fce7.
2026/08/21 14:39:45 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:46 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/95d2852494c64391bd0543525a7e39eb.
2026/08/21 14:39:46 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/b2f2a95a8c4c47a5a501af6a08de830c.
2026/08/21 14:39:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:48 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/2d238787e8854ebca785ae69be3a9fc3.
2026/08/21 14:39:48 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:50 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/3187ca7c23d64019a79045f7e933e470.
2026/08/21 14:39:50 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:50 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:51 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/4d87e8c079b3475fadd7cc1a6d73ae2f.
2026/08/21 14:39:51 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:52 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:52 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/894bc7fda5f041928e8709995fb888d3.
2026/08/21 14:39:52 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.
2026/08/21 14:39:54 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:39:54 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/792064299553530657/runs/50399aa73dea4c72a1f22d57c28b5267.
2026/08/21 14:39:54 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/792064299553530657.

2026/08/21 14:40:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:40:59 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/19cb907108fe4efb89aa8b59da389420.
2026/08/21 14:40:59 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:00 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:01 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/56be9d1d43914fb2a8e348f98d6b86b1.
2026/08/21 14:41:01 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:03 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:03 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/a84df7c26da84169bc1ac400ff280db9.
2026/08/21 14:41:03 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:04 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:05 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/d814d8225e054768acc36fde24fa1351.
2026/08/21 14:41:05 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:06 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/2e7234ea384f4725bc97ab4d2546fd9c.
2026/08/21 14:41:06 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:08 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/4e10454ea21c41d796b4745a7a560fb5.
2026/08/21 14:41:08 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:09 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/60cce569084d401bb774d849e7f558eb.
2026/08/21 14:41:09 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:10 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:11 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/919ed7759d4942d09a2f8c9409cca8f6.
2026/08/21 14:41:11 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:11 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:12 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/b3ac50079eeb4e48b381486424a1b775.
2026/08/21 14:41:12 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:14 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/a8363e085ed04769897b99430cff5993.
2026/08/21 14:41:14 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:15 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/b1b3418853b64e2bac26a7b750a54a62.
2026/08/21 14:41:15 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:17 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:17 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/578aea12799540249657c998a3088a10.
2026/08/21 14:41:17 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:18 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:19 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/10f9a4666d6342d2815b7388fc24cd0f.
2026/08/21 14:41:19 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:20 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:20 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/fa77a4eef274416ea9b44e7cdd157203.
2026/08/21 14:41:20 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.
2026/08/21 14:41:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:41:21 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/970786522064379019/runs/7fd3264ccdec44419d5099e2c4f986bf.
2026/08/21 14:41:21 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/970786522064379019.

2026/08/21 14:42:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:42:56 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/9d3c173ba6d74467a5f9bbe017e98c05.
2026/08/21 14:42:56 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:42:57 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:42:58 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/73ecf536e07d45a28e8aeedbafd4fc3a.
2026/08/21 14:42:58 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:42:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:43:00 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/6cced9faa7504527b57d12a668b4276f.
2026/08/21 14:43:00 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:43:01 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:43:02 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/f327f9b7291540d2a37a75f1a35da175.
2026/08/21 14:43:02 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:43:03 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:43:03 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/681b03262c0e47169acf36e6c6213c49.
2026/08/21 14:43:03 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:43:04 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:43:04 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/d74905d0dbb6442d9165882eaaf2636f.
2026/08/21 14:43:04 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:43:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:43:05 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/c81b40455ce043409eddb7b7727e9fc4.
2026/08/21 14:43:05 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:43:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:43:06 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/b8c6404be2d94988a55a658fae372d50.
2026/08/21 14:43:06 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:43:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:43:08 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/4fe1defc2468448394f32a3b9d6ac7fd.
2026/08/21 14:43:08 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:43:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:43:09 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/97d5acfdafc146df979467dc849de716.
2026/08/21 14:43:09 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:43:11 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:43:11 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/c75a49ba13ae448a982bb4606bd765ed.
2026/08/21 14:43:11 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:43:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:43:12 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/408c7cf70aa144aeb0d486f9fcc9abd5.
2026/08/21 14:43:12 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:43:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:43:14 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/6b90f9f8564540f8acdcec2a093d19b7.
2026/08/21 14:43:14 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:43:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:43:15 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/b9fcef20ada6479bb6d35abc6d8567d5.
2026/08/21 14:43:15 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.
2026/08/21 14:43:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:43:16 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/724007551832015283/runs/e7c7cf64d15d486ea901f594da2e9618.
2026/08/21 14:43:16 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/724007551832015283.

2026/08/21 14:44:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:26 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/304cd4a4d54441caad584b7220507d1f.
2026/08/21 14:44:26 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:27 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:27 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/1d891822c85b4d96913e641e40fb7cda.
2026/08/21 14:44:27 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:28 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:29 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/4f018018b9184775850d366f9c1247a9.
2026/08/21 14:44:29 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:30 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:30 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/c7310a5bc98c46ea87fa0bb9e78fe7b9.
2026/08/21 14:44:30 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:31 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/d1b7db8601e04b7ea314ad9495ecdda8.
2026/08/21 14:44:31 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:33 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:33 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/2f3c46fa4aed48dcafaf4d5ecb3d5290.
2026/08/21 14:44:33 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:34 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:34 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/3dce928646ce41b788e362f9e190105e.
2026/08/21 14:44:34 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:36 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/92e37085784040708f07f01fb2362153.
2026/08/21 14:44:36 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:37 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/641b5191875a4e4183ed29c605d7ef96.
2026/08/21 14:44:37 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:38 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/cd6a7824214b4e78ac5397c2df5ccda1.
2026/08/21 14:44:38 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:39 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:39 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/68c3041896864a0ba424ea96f3dd95e1.
2026/08/21 14:44:39 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:40 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/c811afe9d6254574bf9708992fa94bc4.
2026/08/21 14:44:40 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:41 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/fc880f6426c44455bd415ab89bfac0c0.
2026/08/21 14:44:41 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:43 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/917a873947f740f89f22918aae13bc6b.
2026/08/21 14:44:43 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.
2026/08/21 14:44:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:44:44 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/547488384255783920/runs/1068603a1a7c4d6f8051ec0bd989ce2e.
2026/08/21 14:44:44 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/547488384255783920.

2026/08/21 14:46:23 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:23 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/4ecd0a95b98447e4b999fea73ff48e95.
2026/08/21 14:46:23 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:24 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:24 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/1cf52ffcd40840e4900ff42f2bd095c1.
2026/08/21 14:46:24 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:26 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/8596f365cb404ef3bc77b97fa5827a54.
2026/08/21 14:46:26 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:27 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:28 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/3311c993a426488a849899ecbd48323b.
2026/08/21 14:46:28 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:30 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:30 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/ec2f9be1f83e4a82a7868bc46bf5f9fb.
2026/08/21 14:46:30 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:32 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:32 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/fe683ce8dad64c9eaef20390719ede80.
2026/08/21 14:46:32 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:33 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:34 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/85d99d294125401d95077e6fcd01346c.
2026/08/21 14:46:34 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:35 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/1716ae57f0214b3fa15151b23c721c1f.
2026/08/21 14:46:35 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:37 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:37 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/7e664df670d9431fa46f99308a6c76e8.
2026/08/21 14:46:37 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:38 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/43328c4f4e9748e0b363ed5c8c8940ec.
2026/08/21 14:46:38 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:40 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/a7667a7794514ebf97efc555784e2148.
2026/08/21 14:46:40 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:42 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/d54a137db9e5417ba5a3c1723976f058.
2026/08/21 14:46:42 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:43 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/5b6ae346814a4b86998914776c5a2f5f.
2026/08/21 14:46:43 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:45 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/fe9efe64dd384489ae574274221de02f.
2026/08/21 14:46:45 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.
2026/08/21 14:46:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:46:46 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/593697402102302744/runs/7a196df5467145e69a29faf84b5a640f.
2026/08/21 14:46:46 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/593697402102302744.

2026/08/21 14:47:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:42 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/fd6306d1eace4548b614506bd00a6c05.
2026/08/21 14:47:42 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:47:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:44 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/79da45ba0f424c00a814838b755a934c.
2026/08/21 14:47:44 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:47:45 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:45 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/9fe74c01bba94a9a9436503c7885c685.
2026/08/21 14:47:45 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:47:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/45d9a5d628ab45a5932ac27d4c244c86.
2026/08/21 14:47:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:47:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:48 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/a1c2bcce9e2c473ab76a69ff5c0cae47.
2026/08/21 14:47:48 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:47:50 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:51 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/ab8f0811dad04b8bac42b532b255537c.
2026/08/21 14:47:51 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:47:52 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:52 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/3a2e9fccfec742edbe3cb0d07899afb1.
2026/08/21 14:47:52 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:47:53 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:53 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/8135b967384d4adfa634a48960d6a27d.
2026/08/21 14:47:53 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:47:54 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:54 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/04e6443b73e24d8bbae9f995fe787585.
2026/08/21 14:47:54 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:47:55 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:55 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/cae8aba5bad1440ebc111aa877ebbe9e.
2026/08/21 14:47:55 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:47:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:56 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/c1ac4890a1b64ecca4babad7906e263f.
2026/08/21 14:47:56 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:47:57 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:57 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/c51c99b4c22b434992202d0cf9adf545.
2026/08/21 14:47:57 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:47:58 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:58 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/9f20dfe751b24e4a8b2a9434adb45233.
2026/08/21 14:47:58 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:47:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:47:59 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/17e855e55f304adc92b095c2bbfed172.
2026/08/21 14:47:59 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.
2026/08/21 14:48:00 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:00 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/521733049710212400/runs/e7d941542ce64e1993f8b053cfa06bcf.
2026/08/21 14:48:00 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/521733049710212400.

2026/08/21 14:48:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:35 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/7a0592a668924401bfab6fe3cf5eb81e.
2026/08/21 14:48:35 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:37 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/47e7a3e570044248b33a2b71d425fe09.
2026/08/21 14:48:37 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:37 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:38 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/09d3335c17c44eed9401bee21ced15c1.
2026/08/21 14:48:38 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:39 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/e32f6a3c4c0f4038ac7e58cb56c8fa7e.
2026/08/21 14:48:39 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:40 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/7ec74d9ea1344414ad64555151175d26.
2026/08/21 14:48:40 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:41 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/769df03b6e584dba8739b098c659221e.
2026/08/21 14:48:41 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:42 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/82ebc89681444b779f4133c67ad07a02.
2026/08/21 14:48:42 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:43 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/887ace63a33a4ebeb16d2bac81aed64f.
2026/08/21 14:48:43 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:44 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/140f4e128f66452fa31aee03648aa5f3.
2026/08/21 14:48:44 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:45 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:45 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/3226e97058c6452d99e47bf450e7ef08.
2026/08/21 14:48:45 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:47 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/aec63fd1812c49bb83a7212a4a8bd42c.
2026/08/21 14:48:47 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:48 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/473fd154a3074bcfa9ad6c143550b895.
2026/08/21 14:48:48 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:49 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/7174d086370742f1b967fb9c11185d8a.
2026/08/21 14:48:49 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:50 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:50 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/3d68016d5be44519ac5f94591a5638bc.
2026/08/21 14:48:50 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.
2026/08/21 14:48:51 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:48:51 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/744174544818870760/runs/c5a88cf01ee54ccb8f255001b93843b3.
2026/08/21 14:48:51 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/744174544818870760.

2026/08/21 14:49:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:15 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/59bf82fc662f47fb84863306958d1294.
2026/08/21 14:49:15 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:16 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/350aa219a6484681b2e79d7ad69ce6e8.
2026/08/21 14:49:16 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:17 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:17 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/f17c09268e994941837ce75988739488.
2026/08/21 14:49:17 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:18 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:18 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/71e627dff23c43eea3246fe0408b7647.
2026/08/21 14:49:18 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:19 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:19 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/63f4b2af78494509bdcb9e69e8c0b320.
2026/08/21 14:49:19 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:20 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:20 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/14a7bdc0223c4cbab1693ea6f98c8b55.
2026/08/21 14:49:20 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:21 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/2a9861144de24fd999790a1bf51756f6.
2026/08/21 14:49:21 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:22 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:22 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/5af057d197a643b9af68adead68c0837.
2026/08/21 14:49:22 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:23 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:23 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/d3830d96e27d4d97a21f3e42e8d1edab.
2026/08/21 14:49:23 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:24 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:25 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/ad2394de23da471b8b86f274b6f1e6c7.
2026/08/21 14:49:25 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:26 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/c85330d49e6247e38fd06bb31c5624e5.
2026/08/21 14:49:26 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:27 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/dded116f07364b01a0ce8e2e2a675e12.
2026/08/21 14:49:27 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:27 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:28 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/7d067ff21567496782075ff6d828c6a8.
2026/08/21 14:49:28 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:28 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:29 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/65c868d945db4c6880c6fa2fb368aa3f.
2026/08/21 14:49:29 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.
2026/08/21 14:49:29 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:49:30 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/654988368524884403/runs/4f878be9e21a4b51a8aa90752cfe75f8.
2026/08/21 14:49:30 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/654988368524884403.

2026/08/21 14:50:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:05 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/f6779691d26a49899c7716ff6fc4ad63.
2026/08/21 14:50:05 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:07 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:07 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/244ce66557524db78544f76b96ef4580.
2026/08/21 14:50:07 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:08 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/fb62f60fa8dd499fb429227e4160232f.
2026/08/21 14:50:08 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:09 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/b890fe394dd644b598b200244e75f569.
2026/08/21 14:50:09 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:10 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:11 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/563b490962124e038b51df3cfc266da8.
2026/08/21 14:50:11 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:12 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/e1de9c90952149b9b11b63623c30b883.
2026/08/21 14:50:12 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:14 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/d157115b4b7240c3be38b27adfaaa582.
2026/08/21 14:50:14 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:15 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/4a673eea8ad9417789709ff2d643e1ea.
2026/08/21 14:50:15 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:16 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/58307b96630546e298af562e5118a9a6.
2026/08/21 14:50:16 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:17 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:17 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/231142c176d949549a1a79072e468668.
2026/08/21 14:50:17 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:18 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:19 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/93310b6d94084c21a28c14ace97659d1.
2026/08/21 14:50:19 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:20 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:20 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/242612c143014b7cb0be073ec40c4e00.
2026/08/21 14:50:20 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:21 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/c9d92fa7e07b4e8eb8ab87b3ec81ba1f.
2026/08/21 14:50:21 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:22 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:23 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/11238d211aed460aabcdf88f10d9c146.
2026/08/21 14:50:23 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.
2026/08/21 14:50:23 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:24 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/186186757358555782/runs/f72b58412d40474ba1bd54b44b148c97.
2026/08/21 14:50:24 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/186186757358555782.

2026/08/21 14:50:53 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:53 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/2e62c0e2280049c28625271751d8686b.
2026/08/21 14:50:53 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:50:54 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:50:55 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/ac7e885d58c145069b70e8a92d9522e1.
2026/08/21 14:50:55 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:51:11 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:51:12 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/42d5e2a005994aa8a06722ef8d2e1210.
2026/08/21 14:51:12 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:51:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:51:13 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/5dfc8d771afc4f55b159bfa5745ab603.
2026/08/21 14:51:13 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:51:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:51:15 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/67e5cc354508419ea8a8c068899d56f9.
2026/08/21 14:51:15 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:51:37 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:51:46 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/059795a88e7342eeb9361aa1d8c51314.
2026/08/21 14:51:46 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:51:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:51:57 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/805132368c1e432284c6332a00fb0c54.
2026/08/21 14:51:57 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:51:58 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:51:58 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/db36f6b479d24aa288c293366e30a85b.
2026/08/21 14:51:58 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:52:00 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:52:01 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/85d79a5a457c476ea2b1a7490a04990e.
2026/08/21 14:52:01 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:52:03 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:52:03 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/ec6cf4447e1e47a69c625e1ab64db0f8.
2026/08/21 14:52:03 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:52:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:52:05 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/50b81186a5534f23b9e2a11a5f568f13.
2026/08/21 14:52:05 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:52:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:52:07 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/c966c607000b41e187c5e1fcaa7ddefc.
2026/08/21 14:52:07 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:52:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:52:08 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/0ee64a3bfe5a476b80a96031c1264a94.
2026/08/21 14:52:08 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:52:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:52:10 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/88f564e7fe5f4509a384a133e067fc9e.
2026/08/21 14:52:10 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.
2026/08/21 14:52:11 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:52:11 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/932104112248218172/runs/beabafd440fa4806902fa74e959381a5.
2026/08/21 14:52:11 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/932104112248218172.

2026/08/21 14:55:04 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:04 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/ccd7e059a5af43ba906d4bb0433e26fb.
2026/08/21 14:55:04 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:05 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/ad21fd7b83d9428994624bd8cbbd20e7.
2026/08/21 14:55:05 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:06 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/830c9ad6156145088aa085e6853cf883.
2026/08/21 14:55:07 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:08 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/0efa8427970e48d9ab4fc44845b698fb.
2026/08/21 14:55:08 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:09 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/87e37a69bb9148f29910e4b5dffde0ab.
2026/08/21 14:55:09 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:10 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:10 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/b13d7b82013b479c963ecc545ab92985.
2026/08/21 14:55:10 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:11 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:11 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/19f69d61a7584c8ca16a9cd14e803147.
2026/08/21 14:55:11 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:12 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/bfce9245d2fb48dfbf6a540a99161a7e.
2026/08/21 14:55:12 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:14 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/e15c1c897f3e41ef8d2dac1db2567a32.
2026/08/21 14:55:14 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:15 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/65298f9879e340fc92ef00351b391717.
2026/08/21 14:55:15 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:16 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/1b758ec161484ae5957a1980f086335a.
2026/08/21 14:55:16 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:17 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:18 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/8c137f54073a47909a0b676494324367.
2026/08/21 14:55:18 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:18 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:19 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/7472dc464c454f139d3fb208f89fedc0.
2026/08/21 14:55:19 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:20 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:20 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/97fd65b0d06b4c4a8678717e3a1367cf.
2026/08/21 14:55:20 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.
2026/08/21 14:55:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:55:21 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/668694462194489806/runs/0c22557955c94528a357ebfb65c2fbb0.
2026/08/21 14:55:21 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/668694462194489806.

2026/08/21 14:56:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:42 INFO mlflow.tracking._tracking_service.client: 🏃 View run SVM - Linear Kernel at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/3744a334b1a34b5eb78d982457dbfd09.
2026/08/21 14:56:42 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:56:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:43 INFO mlflow.tracking._tracking_service.client: 🏃 View run Naive Bayes at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/03676fdaa0dc44a596a9f89e93d3c730.
2026/08/21 14:56:43 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:56:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:44 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ridge Classifier at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/13ea0561bd0a4b829c4197c9aba3079a.
2026/08/21 14:56:44 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:56:45 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:45 INFO mlflow.tracking._tracking_service.client: 🏃 View run Linear Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/8202129afe76447997bd5b3aa5fcfdc8.
2026/08/21 14:56:45 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:56:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:46 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/b471a850a1134ba78e185660974b2699.
2026/08/21 14:56:46 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:56:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:48 INFO mlflow.tracking._tracking_service.client: 🏃 View run K Neighbors Classifier at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/d255ac203d004db4a48af55206ee7c05.
2026/08/21 14:56:48 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:56:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:49 INFO mlflow.tracking._tracking_service.client: 🏃 View run Decision Tree Classifier at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/d61d01898203497c911c10f47d893717.
2026/08/21 14:56:49 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:56:50 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:50 INFO mlflow.tracking._tracking_service.client: 🏃 View run Quadratic Discriminant Analysis at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/39bcd4ae3ae14f3e808bfc8f11d3e4e9.
2026/08/21 14:56:50 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:56:51 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:52 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest Classifier at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/54e72b82a5c74210a4e69cf2e364a77d.
2026/08/21 14:56:52 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:56:53 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:53 INFO mlflow.tracking._tracking_service.client: 🏃 View run Ada Boost Classifier at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/0b6f76bc929646758c6a98d8dbd64bd1.
2026/08/21 14:56:53 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:56:54 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:54 INFO mlflow.tracking._tracking_service.client: 🏃 View run Gradient Boosting Classifier at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/513a876bd4b943c6ab44cfa45047bf69.
2026/08/21 14:56:54 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:56:55 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:55 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extra Trees Classifier at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/c61c69c589ea4a8ea52a2082ebe8c8c7.
2026/08/21 14:56:55 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:56:57 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:57 INFO mlflow.tracking._tracking_service.client: 🏃 View run Extreme Gradient Boosting at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/eeeadbb601834a3dbafb7b01a96e275c.
2026/08/21 14:56:57 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:56:58 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:56:58 INFO mlflow.tracking._tracking_service.client: 🏃 View run CatBoost Classifier at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/cde7f65578b34e2d8a38614a81a88e12.
2026/08/21 14:56:58 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.
2026/08/21 14:57:00 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2026/08/21 14:57:00 INFO mlflow.tracking._tracking_service.client: 🏃 View run Dummy Classifier at: http://127.0.0.1:5000/#/experiments/479745575655938716/runs/9b78206ed988429584b1e926b80d2b66.
2026/08/21 14:57:00 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/479745575655938716.

## Compare Models

In [6]:
performance_comparison = pd.DataFrame(
    {
        "With Age and BMI": {disease: results["F1"].max() for disease, results in comp_results["with"].items()},
        "Without Age and BMI": {disease: results["F1"].max() for disease, results in comp_results["without"].items()},
    }
)

performance_comparison["Better Setup"] = performance_comparison.idxmax(axis=1)
performance_comparison

,With Age and BMI,Without Age and BMI,Better Setup
Heart Disease,0.3167,0.3545,Without Age and BMI
Diabetes,0.2742,0.2821,Without Age and BMI
Stroke,0.2127,0.1996,With Age and BMI
Kidney Disease,0.2131,0.2341,Without Age and BMI
Cancer,0.1886,0.1617,With Age and BMI
Alzheimer's Disease,0.2171,0.2415,Without Age and BMI
COPD,0.2188,0.2117,With Age and BMI
Liver Disease,0.2465,0.2266,With Age and BMI
Parkinson's Disease,0.1277,0.1219,With Age and BMI
Tuberculosis,0.0800,0.0598,With Age and BMI